export class UsuarioGitRepositorio{

              public id: number = 0;
              public node_id: string = '';
              public name: string = '';
              public full_name: string = '';
              public private: boolean = false;
              public owner: any;
              public html_url: string = '';
              public description: string = '';
              public fork: boolean = false;
              public url: string = '';
              public forks_url:string = '';
              public keys_url: string = '';
              public collaborators_url:string = '';
              public teams_url: string = '';
              public hooks_url: string = '';
              public issue_events_url: string = '';
              public events_url: string = '';
              public assignees_url: string = '';
              public branches_url: string = '';
              public tags_url: string = '';
              public blobs_url: string = '';
              public git_tags_url: string = '';
              public git_refs_url: string = '';
              public trees_url: string = '';
              public statuses_url: string = '';
              public languages_url:string = '';
              public stargazers_url: string = '';
              public contributors_url: string = '';
              public subscribers_url: string = '';
              public subscription_url: string = '';
              public commits_url: string = '';
              public git_commits_url: string = '';
              public comments_url: string = '';
              public issue_comment_url: string = '';
              public contents_url: string = '';
              public compare_url: string = '';
              public merges_url: string = '';
              public archive_url: string = '';
              public downloads_url: string = '';
              public issues_url: string = '';
              public pulls_url: string = '';
              public milestones_url: string = '';
              public notifications_url: string = '';
              public labels_url: string = '';
              public releases_url: string = '';
              public deployments_url: string = '';
              public created_at: any;
              public updated_at:  any;
              public pushed_at:  any;
              public git_url: string = '';
              public ssh_url: string = '';
              public clone_url:string = '';
              public svn_url: string = '';
              public homepage: string = '';
              public size: number = 0;
              public stargazers_count: number = 0;
              public watchers_count: number = 0;
              public language: string = '';
              public has_issues:boolean = false;
              public has_projects: boolean = false;
              public has_downloads: boolean = false;
              public has_wiki: boolean = false;
              public has_pages: boolean = false;
              public forks_count: number = 0;
              public mirror_url: string = '';
              public archived: boolean = false;
              public disabled: boolean = false;
              public open_issues_count: number = 0;
              public license: any;
              public forks:number = 0;
              public open_issues: number = 0;
              public watchers: number = 0;
              public default_branch:string = '';
          }

